CREATE TABLE bears (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) ,
  age INTEGER NOT NULL,
  sex VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL,
  temperament VARCHAR(255) NOT NULL,
  alive INTEGER NOT NULL
);